# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: OAuth2 CI/CD

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: gradlew 권한 설정
        run: chmod +x gradlew

      - name: naver.properties 추가
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_api: ${{ secrets.NAVER_API }}
          envkey_secret: ${{ secrets.NAVER_SECRET }}
          envkey_callback: ${{ secrets.NAVER_CALLBACK }}
          directory: ./src/main/webapp/WEB-INF
          file_name: naver.properties

      - name: google.properties 추가
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_api: ${{ secrets.GOOGLE_API }}
          envkey_secret: ${{ secrets.GOOGLE_SECRET }}
          envkey_callback: ${{ secrets.GOOGLE_CALLBACK }}
          directory: ./src/main/webapp/WEB-INF
          file_name: google.properties

      - name: kakao.properties 추가
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_api: ${{ secrets.KAKAO_API }}
          envkey_secret: ${{ secrets.KAKAO_SECRET }}
          envkey_callback: ${{ secrets.KAKAO_CALLBACK }}
          directory: ./src/main/webapp/WEB-INF
          file_name: kakao.properties

      - name: github.properties 추가
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_api: ${{ secrets.GH_API }}
          envkey_secret: ${{ secrets.GH_SECRET }}
          envkey_callback: ${{ secrets.GH_CALLBACK }}
          directory: ./src/main/webapp/WEB-INF
          file_name: github.properties

      - name: Gradle 빌드
        run: ./gradlew build

      - name: SSH 배포
        uses: appleboy/scp-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "./build/libs/oauth2.war"
          target: ${{ secrets.TARGET }}
          strip_components: 3